# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product_search.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14product_search.proto\x12\rproductlookup\"%\n\x14SearchProductRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\x90\x01\n\x0bProductData\x12\x0e\n\x06sku_id\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\r\n\x05\x62rand\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\t\x12\x13\n\x0bproduct_url\x18\x06 \x01(\t\x12\x13\n\x0bpart_number\x18\x07 \x01(\t\"E\n\x15SearchProductResponse\x12,\n\x08products\x18\x01 \x03(\x0b\x32\x1a.productlookup.ProductData2m\n\rProductSearch\x12\\\n\rSearchProduct\x12#.productlookup.SearchProductRequest\x1a$.productlookup.SearchProductResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_search_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SEARCHPRODUCTREQUEST']._serialized_start=39
  _globals['_SEARCHPRODUCTREQUEST']._serialized_end=76
  _globals['_PRODUCTDATA']._serialized_start=79
  _globals['_PRODUCTDATA']._serialized_end=223
  _globals['_SEARCHPRODUCTRESPONSE']._serialized_start=225
  _globals['_SEARCHPRODUCTRESPONSE']._serialized_end=294
  _globals['_PRODUCTSEARCH']._serialized_start=296
  _globals['_PRODUCTSEARCH']._serialized_end=405
# @@protoc_insertion_point(module_scope)
