# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import product_search_pb2 as product__search__pb2


class ProductSearchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchProduct = channel.unary_unary(
                '/productlookup.ProductSearch/SearchProduct',
                request_serializer=product__search__pb2.SearchProductRequest.SerializeToString,
                response_deserializer=product__search__pb2.SearchProductResponse.FromString,
                )


class ProductSearchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductSearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchProduct,
                    request_deserializer=product__search__pb2.SearchProductRequest.FromString,
                    response_serializer=product__search__pb2.SearchProductResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'productlookup.ProductSearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProductSearch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/productlookup.ProductSearch/SearchProduct',
            product__search__pb2.SearchProductRequest.SerializeToString,
            product__search__pb2.SearchProductResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
